services:
  mysql:
    image: mysql:8.0
    build: .
    restart: always
    container_name: oa_gk_mysql_django
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3312:3306"
    volumes:
      - oa_gk_volume:/var/lib/mysql
    networks:
      - oa_network
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]

  phpmyadmin_gatekeeper:
    image: phpmyadmin/phpmyadmin
    container_name: oa_gk_phpmyadmin_django
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8088:80"
    networks:
      - oa_network
    depends_on:
      - mysql

volumes:
  oa_gk_volume: {}

networks:
  oa_network:
    driver: bridge
