# Generated by Codex on 2026-03-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aegis", "0005_alter_permissionmaster_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceScopeAssignment",
            fields=[
                ("id", models.AutoField(blank=False, db_column="id", db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name="ID")),
                ("status", models.SmallIntegerField(choices=[(1, "Active"), (0, "Inactive"), (2, "Deleted")], default=1, verbose_name="Status")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("role", models.CharField(default="viewer", max_length=50)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("scope_type", models.CharField(choices=[("farm", "farm"), ("parcel", "parcel")], max_length=20)),
                ("scope_id", models.UUIDField(db_index=True)),
                ("group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="service_scope_assignments", to="auth.group")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scope_assignments", to="aegis.servicemaster")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="service_scope_assignments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Service Scope Assignment",
                "verbose_name_plural": "Service Scope Assignments",
                "db_table": "service_scope_assignments",
            },
        ),
        migrations.AddIndex(
            model_name="servicescopeassignment",
            index=models.Index(fields=["scope_type", "scope_id"], name="ssa_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="servicescopeassignment",
            index=models.Index(fields=["service", "status"], name="ssa_service_status_idx"),
        ),
        migrations.AddIndex(
            model_name="servicescopeassignment",
            index=models.Index(fields=["user", "status"], name="ssa_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="servicescopeassignment",
            index=models.Index(fields=["group", "status"], name="ssa_group_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="servicescopeassignment",
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(user__isnull=False, group__isnull=True))
                    | (models.Q(user__isnull=True, group__isnull=False))
                ),
                name="ssa_exactly_one_subject",
            ),
        ),
    ]
