# Generated by Codex on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aegis", "0006_servicescopeassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmCalendarResourceCache",
            fields=[
                ("id", models.AutoField(blank=False, db_column="id", db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name="ID")),
                ("status", models.SmallIntegerField(choices=[(1, "Active"), (0, "Inactive"), (2, "Deleted")], default=1, verbose_name="Status")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("resource_type", models.CharField(choices=[("farm", "farm"), ("parcel", "parcel")], db_index=True, max_length=20)),
                ("resource_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("farm_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "verbose_name": "FarmCalendar Resource Cache",
                "verbose_name_plural": "FarmCalendar Resource Cache",
                "db_table": "farmcalendar_resource_cache",
                "unique_together": {("resource_type", "resource_id")},
            },
        ),
        migrations.AddIndex(
            model_name="farmcalendarresourcecache",
            index=models.Index(fields=["resource_type", "status"], name="fcrc_type_status_idx"),
        ),
        migrations.AddIndex(
            model_name="farmcalendarresourcecache",
            index=models.Index(fields=["farm_id", "status"], name="fcrc_farm_status_idx"),
        ),
        migrations.AddIndex(
            model_name="farmcalendarresourcecache",
            index=models.Index(fields=["synced_at"], name="fcrc_synced_idx"),
        ),
    ]
