# Generated by Django 5.1.4 on 2026-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0006_servicescopeassignment'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmenumaster',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='historicaladminmenumaster',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='historicaladminmenumaster',
            name='history_user',
        ),
        migrations.RemoveConstraint(
            model_name='servicescopeassignment',
            name='ssa_exactly_one_subject',
        ),
        migrations.AddConstraint(
            model_name='servicescopeassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('group__isnull', True)), models.Q(('user__isnull', True), ('group__isnull', False)), _connector='OR'), name='ssa_exactly_one_subject'),
        ),
        migrations.DeleteModel(
            name='AdminMenuMaster',
        ),
        migrations.DeleteModel(
            name='HistoricalAdminMenuMaster',
        ),
    ]
