# Generated by Codex on 2026-03-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aegis", "0007_farmcalendarresourcecache"),
        ("aegis", "0007_remove_adminmenumaster_parent_id_and_more"),
    ]

    operations = []
