# Generated by Django 6.0.3 on 2026-03-26 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0010_servicerole_and_scope_role_ref'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenant',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='defaultauthuserextend',
            name='is_tenant_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldefaultauthuserextend',
            name='is_tenant_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultauthuserextend',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='aegis.tenant'),
        ),
        migrations.AddField(
            model_name='farmcalendarresourcecache',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fc_resources', to='aegis.tenant'),
        ),
        migrations.AddField(
            model_name='groupserviceaccess',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_service_links', to='aegis.tenant'),
        ),
        migrations.AddField(
            model_name='historicaldefaultauthuserextend',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aegis.tenant'),
        ),
        migrations.AddField(
            model_name='servicescopeassignment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_scope_assignments', to='aegis.tenant'),
        ),
        migrations.AddIndex(
            model_name='farmcalendarresourcecache',
            index=models.Index(fields=['tenant', 'status'], name='fcrc_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicescopeassignment',
            index=models.Index(fields=['tenant', 'status'], name='ssa_tenant_status_idx'),
        ),
    ]
