# Generated by Django 6.0.3 on 2026-04-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0013_tenant_scoped_service_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerole',
            options={'ordering': ('tenant__code', 'service__service_code', 'role_name'), 'verbose_name': 'Service Role', 'verbose_name_plural': 'Service Roles'},
        ),
        migrations.AlterModelOptions(
            name='servicescopeassignment',
            options={'verbose_name': 'Role Grant', 'verbose_name_plural': 'Role Grants'},
        ),
    ]
